In [63]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import gmaps
import os
import apikey as api_key
import json
import ipywidgets
from sodapy import Socrata

In [42]:
client = Socrata("data.austintexas.gov", None)
results = client.get("fdj4-gpfu", limit=10000)

# Convert to pandas DataFrame
results_df = pd.DataFrame.from_records(results)
results_df.head()

WARNING:root:Requests made without an app_token will be subject to strict throttling limits.

,incident_report_number,crime_type,ucr_code,family_violence,occ_date_time,occ_date,occ_time,rep_date_time,rep_date,rep_time,...,y_coordinate,latitude,longitude,location,:@computed_region_a3it_2a2z,:@computed_region_8spj_utxs,:@computed_region_q9nd_rr82,:@computed_region_qwte_z96m,clearance_status,clearance_date
0,20205052927,BURGLARY OF RESIDENCE,500,N,2020-12-26T21:00:00.000,2020-12-26T00:00:00.000,2100,2020-12-27T01:39:00.000,2020-12-27T00:00:00.000,139,...,3114950,30.22356137,-97.74198286,"{'latitude': '30.22356137', 'longitude': '-97....",3256,3,3,NaN,NaN,NaN
1,20205052922,CRIMINAL MISCHIEF,1400,N,2020-12-26T19:15:00.000,2020-12-26T00:00:00.000,1915,2020-12-26T21:04:00.000,2020-12-26T00:00:00.000,2104,...,3115747,30.2577883,-97.7385392,"{'latitude': '30.2577883', 'longitude': '-97.7...",2856,9,10,1405,NaN,NaN
2,20205052926,BURGLARY OF RESIDENCE,500,N,2020-12-26T18:15:00.000,2020-12-26T00:00:00.000,1815,2020-12-27T00:35:00.000,2020-12-27T00:00:00.000,35,...,3128567,30.3198665,-97.69622732,"{'latitude': '30.3198665', 'longitude': '-97.6...",3239,1,8,NaN,NaN,NaN
3,20203610751,VIOL CITY ORDINANCE -FIREWORK,3201,N,2020-12-26T15:49:00.000,2020-12-26T00:00:00.000,1549,2020-12-26T15:49:00.000,2020-12-26T00:00:00.000,1549,...,3155722,30.35064627,-97.6092693,"{'latitude': '30.35064627', 'longitude': '-97....",3643,1,8,NaN,NaN,NaN
4,20205052899,THEFT BY SHOPLIFTING,607,N,2020-12-26T15:00:00.000,2020-12-26T00:00:00.000,1500,2020-12-26T17:13:00.000,2020-12-26T00:00:00.000,1713,...,3099020,30.44324238,-97.78664165,"{'latitude': '30.44324238', 'longitude': '-97....",3639,6,6,NaN,NaN,NaN

In [43]:
crime_type= results_df['crime_type']
print(crime_type)

0                BURGLARY OF RESIDENCE
1                    CRIMINAL MISCHIEF
2                BURGLARY OF RESIDENCE
3        VIOL CITY ORDINANCE -FIREWORK
4                 THEFT BY SHOPLIFTING
                     ...
9995                DATING DISTURBANCE
9996                ROBBERY BY ASSAULT
9997     BURGLARY OF VEH-NO SUSPECT/FU
9998    INJ TO ELDERLY   FAM/DATE VIOL
9999     AGG ASSAULT FAM/DATE VIOLENCE
Name: crime_type, Length: 10000, dtype: object

In [44]:
# Import CSV instead
crime_path = "Crime_Reports.csv"
crime_data = pd.read_csv(crime_path)
crime_data.head()

,Incident Number,Highest Offense Description,Highest Offense Code,Family Violence,Occurred Date Time,Occurred Date,Occurred Time,Report Date Time,Report Date,Report Time,...,Census Tract,Clearance Status,Clearance Date,UCR Category,Category Description,X-coordinate,Y-coordinate,Latitude,Longitude,Location
0,2.019157e+10,FRAUD - OTHER,1199,N,6/3/2019 16:00,6/3/2019,1600.0,6/6/2019 17:34,6/6/2019,1734.0,...,203.11,NaN,NaN,NaN,NaN,3097785.0,3097785.0,30.483646,-97.789495,"(30.48364631, -97.7894953)"
1,2.019155e+10,DEADLY CONDUCT,408,N,6/4/2019 3:12,6/4/2019,312.0,6/4/2019 3:16,6/4/2019,316.0,...,18.06,N,6/6/2019,13A,Aggravated Assault,3128227.0,3128227.0,30.346646,-97.696573,"(30.34664576, -97.69657342)"
2,2.019502e+10,THEFT OF LICENSE PLATE,614,N,6/3/2019 15:00,6/3/2019,1500.0,6/4/2019 15:22,6/4/2019,1522.0,...,24.09,N,6/4/2019,23G,Theft,3098393.0,3098393.0,30.205267,-97.794900,"(30.20526729, -97.79490043)"
3,2.020501e+10,RUNAWAY CHILD,4100,N,2/22/2020 18:00,2/22/2020,1800.0,2/24/2020 18:03,2/24/2020,1803.0,...,NaN,N,3/3/2020,NaN,NaN,3155456.0,3155456.0,30.176140,-97.615031,"(30.17613952, -97.6150307)"
4,2.019167e+10,BURGLARY OF RESIDENCE,500,N,6/14/2019 12:00,6/14/2019,1200.0,6/16/2019 22:00,6/16/2019,2200.0,...,17.51,N,9/18/2019,220,Burglary,3111039.0,3111039.0,30.364987,-97.750587,"(30.36498691, -97.75058749)"

In [45]:
crime_types= crime_data['Highest Offense Description']
print(crime_types)

0                       FRAUD - OTHER
1                      DEADLY CONDUCT
2              THEFT OF LICENSE PLATE
3                       RUNAWAY CHILD
4               BURGLARY OF RESIDENCE
                      ...
1048570                         THEFT
1048571    POSS OF DRUG PARAPHERNALIA
1048572    POSS OF DRUG PARAPHERNALIA
1048573    VOCO SOLICITATION PROHIBIT
1048574                    AUTO THEFT
Name: Highest Offense Description, Length: 1048575, dtype: object

In [53]:
# Filter by Crime Type
# DWI, DWI 2ND, LIQUOR LAW VIOLATION/OTHER, 
# DUI - AGE 17 TO 20, DRIVING WHILE INTOX / FELONY, PUBLIC INTOXICATION, POSSESSION OF MARIJUANA

offense_df = crime_data.set_index("Highest Offense Description", drop= False)
offenses_df = (offense_df.loc[offense_df["Highest Offense Description"].isin(["DWI","DWI 2ND","PUBLIC INTOXICATION", 
                                                                           "LIQUOR LAW VIOLATION/OTHER", "DRIVING WHILE INTOX / FELONY",
                                                                          "POSSESSION OF MARIJUANA", "DUI - AGE 17 TO 20"])])
offenses_df.head()

,Incident Number,Highest Offense Description,Highest Offense Code,Family Violence,Occurred Date Time,Occurred Date,Occurred Time,Report Date Time,Report Date,Report Time,...,Census Tract,Clearance Status,Clearance Date,UCR Category,Category Description,X-coordinate,Y-coordinate,Latitude,Longitude,Location
Highest Offense Description,,,,,,,,,,,,,,,,,,,,,
DWI 2ND,2.016152e+09,DWI 2ND,2102,N,1/15/2016 23:08,1/15/2016,2308.0,1/16/2016 0:05,1/16/2016,5.0,...,NaN,C,2/3/2016,NaN,NaN,3099641.0,3099641.0,30.230877,-97.790275,"(30.23087705, -97.79027457)"
DWI,2.019282e+10,DWI,2100,N,10/9/2019 0:39,10/9/2019,39.0,10/9/2019 0:39,10/9/2019,39.0,...,NaN,C,10/9/2019,NaN,NaN,3115403.0,3115403.0,30.267184,-97.739377,"(30.2671839, -97.73937664)"
LIQUOR LAW VIOLATION/OTHER,2.005409e+08,LIQUOR LAW VIOLATION/OTHER,2208,N,1/4/2005 13:37,1/4/2005,1337.0,1/4/2005 13:37,1/4/2005,1337.0,...,NaN,NaN,NaN,NaN,NaN,3111587.0,3111587.0,30.244195,-97.752082,"(30.24419472, -97.75208226)"
POSSESSION OF MARIJUANA,2.019151e+10,POSSESSION OF MARIJUANA,1803,N,5/31/2019 21:23,5/31/2019,2123.0,5/31/2019 21:23,5/31/2019,2123.0,...,21.10,C,5/31/2019,NaN,NaN,3130612.0,3130612.0,30.272451,-97.691043,"(30.27245061, -97.69104259)"
POSSESSION OF MARIJUANA,2.019156e+10,POSSESSION OF MARIJUANA,1803,N,6/5/2019 22:35,6/5/2019,2235.0,6/5/2019 22:35,6/5/2019,2235.0,...,24.19,NaN,NaN,NaN,NaN,3108421.0,3108421.0,30.193941,-97.763449,"(30.19394123, -97.76344868)"

In [54]:
# Drop columns
new_offenses= offenses_df.drop(columns={"Incident Number", "Highest Offense Description",
                                     "Highest Offense Code", "Family Violence", 
                                     "Occurred Date Time", "Report Date Time",
                                     "Report Date", "Report Time", "Census Tract", 
                                     "Clearance Status", "Clearance Date", "Occurred Time",
                                     "UCR Category", "Category Description", 
                                     "Location", "Address", "Location Type", "Council District", 
                                     "APD Sector", "APD District", "PRA"})
new_offenses

,Occurred Date,Zip Code,X-coordinate,Y-coordinate,Latitude,Longitude
Highest Offense Description,,,,,,
DWI 2ND,1/15/2016,78745.0,3099641.0,3099641.0,30.230877,-97.790275
DWI,10/9/2019,78701.0,3115403.0,3115403.0,30.267184,-97.739377
LIQUOR LAW VIOLATION/OTHER,1/4/2005,78704.0,3111587.0,3111587.0,30.244195,-97.752082
POSSESSION OF MARIJUANA,5/31/2019,78721.0,3130612.0,3130612.0,30.272451,-97.691043
POSSESSION OF MARIJUANA,6/5/2019,78744.0,3108421.0,3108421.0,30.193941,-97.763449
...,...,...,...,...,...,...
PUBLIC INTOXICATION,1/14/2003,78701.0,3114632.0,3114632.0,30.268850,-97.741775
DWI 2ND,12/31/2003,78701.0,3114907.0,3114907.0,30.266001,-97.740980
DWI,2/11/2013,78741.0,3127106.0,3127106.0,30.224929,-97.703447
PUBLIC INTOXICATION,5/27/2004,78705.0,3113584.0,3113584.0,30.288170,-97.744577
DWI,7/22/2009,78745.0,3098623.0,3098623.0,30.232335,-97.793461

In [58]:
g_key = "AIzaSyCQRY-TmfYIztg9E8oNyUjEknsy9e7KHNs"
gmaps.configure(api_key= g_key)

In [ ]:
# mapping by zip, export to png
# running API for gun, liquor stores
# mapping heat map, export to png